import 'dart:io';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import '../../engines/git/git_notifier.dart';
import '../../data/remote/github_client.dart';
import '../../engines/scanner/scanner_engine.dart';
import '../../data/models/finding.dart';

class GitPanelScreen extends ConsumerStatefulWidget {
  const GitPanelScreen({super.key});

  @override
  ConsumerState<GitPanelScreen> createState() => _GitPanelScreenState();
}

class _GitPanelScreenState extends ConsumerState<GitPanelScreen> {
  final _commitMsgCtrl = TextEditingController();
  final _ownerCtrl = TextEditingController();
  final _repoCtrl = TextEditingController();
  final _newRepoNameCtrl = TextEditingController();
  final _storage = const FlutterSecureStorage();
  final _githubClient = GitHubClient();
  
  String? _projectPath;
  String _githubUsername = '';
  int _activeTab = 0; // 0 for Link Existing, 1 for Create New
  final Set<String> _selectedFiles = {};

  @override
  void initState() {
    super.initState();
    _loadProfile();
  }

  Future<void> _loadProfile() async {
    final username = await _storage.read(key: 'github_username');
    if (username != null) {
      setState(() => _githubUsername = username);
      _ownerCtrl.text = username;
    }
  }

  Future<void> _pickProject() async {
    try {
      final dir = await getDirectoryPath();
      if (dir != null) {
        setState(() => _projectPath = dir);
        await ref.read(gitProvider.notifier).loadProject(dir);
        await _ensureGitignore(dir);
      }
    } catch (e) {
      _showSnack('Error picking folder: $e');
    }
  }

  Future<void> _ensureGitignore(String dirPath) async {
    final file = File('$dirPath/.gitignore');
    if (!await file.exists()) {
      await file.writeAsString('''
# Standard Gitignore generated by DevGate
.env
build/
.dart_tool/
.pub-cache/
.packages
*.log
node_modules/
''');
      _showSnack('Created a standard .gitignore file to protect secrets.');
    }
  }

  Future<void> _linkExistingRepo() async {
    if (_ownerCtrl.text.isEmpty || _repoCtrl.text.isEmpty) {
      _showSnack('Please fill Owner and Repo.');
      return;
    }
    final token = await _storage.read(key: 'github_access_token');
    if (token == null) {
      _showSnack('Error: No token found. Please complete setup.');
      return;
    }
    if (!ref.read(gitProvider).isGitRepo) {
      await ref.read(gitProvider.notifier).initRepo(_projectPath!);
    }
    await ref.read(gitProvider.notifier).setRemoteWithToken(_ownerCtrl.text, _repoCtrl.text, token);
    _showSnack('Repository Linked Successfully!');
  }

  Future<void> _createNewRepo() async {
    if (_newRepoNameCtrl.text.isEmpty) {
      _showSnack('Please enter a new repository name.');
      return;
    }
    
    // Call GitHub API to create
    _showSnack('Creating repository on GitHub...');
    final success = await _githubClient.createRepository(_newRepoNameCtrl.text, private: true);
    
    if (success) {
      final token = await _storage.read(key: 'github_access_token');
      if (!ref.read(gitProvider).isGitRepo) {
        await ref.read(gitProvider.notifier).initRepo(_projectPath!);
      }
      await ref.read(gitProvider.notifier).setRemoteWithToken(_githubUsername, _newRepoNameCtrl.text, token!);
      _showSnack('🎉 Repository created and linked!');
    } else {
      _showSnack('Failed to create repository. Check if name already exists.');
    }
  }

  void _showSnack(String msg) {
    if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg)));
  }

  Future<void> _safePush() async {
    if (_projectPath == null) return;
    
    _showSnack('Scanning for secrets before pushing...');
    
    // 1. Run local scanner
    final scannerNotifier = ref.read(scannerStateProvider.notifier);
    await scannerNotifier.scanDirectories([_projectPath!]);
    
    // 2. Check for secrets (ignore recommendations)
    final state = ref.read(scannerStateProvider);
    final secrets = state.findings.where((f) => f.type != FindingType.recommendation).toList();
    
    if (secrets.isNotEmpty) {
       if (mounted) {
         showDialog(
           context: context,
           builder: (ctx) => AlertDialog(
             backgroundColor: const Color(0xFF1E1E1E),
             title: const Row(
               children: [
                 Icon(Icons.warning_amber_rounded, color: Colors.redAccent),
                 SizedBox(width: 8),
                 Text('Security Risk Detected!', style: TextStyle(color: Colors.redAccent, fontSize: 18)),
               ],
             ),
             content: Text('Found ${secrets.length} potential secrets in your code. Please review them in the Scanner tab before pushing to GitHub.', style: const TextStyle(color: Colors.white70)),
             actions: [
               TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel Push', style: TextStyle(color: Colors.grey))),
               TextButton(
                 onPressed: () async {
                   Navigator.pop(ctx);
                   _showSnack('Override active. Pushing to GitHub...');
                   await ref.read(gitProvider.notifier).push();
                 }, 
                 child: const Text('Push Anyway', style: TextStyle(color: Colors.redAccent))
               ),
             ]
           )
         );
       }
       return;
    }

    _showSnack('Scan passed! Pushing to GitHub...');
    await ref.read(gitProvider.notifier).push();
  }

  @override
  Widget build(BuildContext context) {
    final git = ref.watch(gitProvider);
    final isBusy = git.operation != GitOperation.idle;

    return Scaffold(
      backgroundColor: const Color(0xFF131314),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final bool isMobile = constraints.maxWidth < 800;
          
          final mainContent = SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Workspace Integration', style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Colors.white)),
                const SizedBox(height: 8),
                const Text('Manage your local code and sync directly with GitHub securely.', style: TextStyle(color: Colors.grey, fontSize: 14)),
                const SizedBox(height: 32),

                // Project Picker
                _buildProjectPicker(),
                const SizedBox(height: 24),

                if (_projectPath != null) ...[
                  if (!git.isGitRepo || git.remoteUrl.isEmpty)
                    _buildSetupWizard(isBusy)
                  else
                    _buildCommitFlow(git, isBusy),
                ]
              ],
            ),
          );

          final sideBar = Container(
            width: isMobile ? double.infinity : 300,
            decoration: BoxDecoration(
              color: const Color(0xFF1E1E1E),
              border: isMobile 
                  ? const Border(top: BorderSide(color: Color(0xFF3C4043)))
                  : const Border(left: BorderSide(color: Color(0xFF3C4043))),
            ),
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildProfileBadge(),
                const SizedBox(height: 32),
                const Text('AI Recommendations', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white)),
                const SizedBox(height: 16),
                _buildRecommendationCard(
                  'Use .gitignore',
                  'Before pushing to GitHub, ensure you have a .gitignore file to avoid exposing local secrets like .env files.',
                  Icons.shield_outlined,
                  Colors.green,
                ),
                const SizedBox(height: 12),
                _buildRecommendationCard(
                  'Atomic Commits',
                  'Try to commit small, logical units of work. Avoid large "Save everything" commits to keep your history clean.',
                  Icons.commit,
                  const Color(0xFF8AB4F8),
                ),
                
                if (git.operationOutput.isNotEmpty) ...[
                  const SizedBox(height: 32),
                  const Text('Terminal Output', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white)),
                  const SizedBox(height: 12),
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(color: Colors.black45, borderRadius: BorderRadius.circular(8)),
                    child: Text(git.operationOutput, style: TextStyle(color: git.hasError ? Colors.redAccent : Colors.greenAccent, fontFamily: 'monospace', fontSize: 12)),
                  )
                ]
              ],
            ),
          );

          if (isMobile) {
            return SingleChildScrollView(
              child: Column(
                children: [
                  mainContent,
                  sideBar,
                ],
              ),
            );
          }

          return Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(flex: 2, child: mainContent),
              sideBar,
            ],
          );
        },
      ),
    );
  }

  Widget _buildProjectPicker() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(color: const Color(0xFF1E1E1E), borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFF3C4043))),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(color: const Color(0xFF8AB4F8).withValues(alpha: 0.1), shape: BoxShape.circle),
            child: const Icon(Icons.folder, color: Color(0xFF8AB4F8)),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Current Local Directory', style: TextStyle(color: Colors.grey, fontSize: 12)),
                const SizedBox(height: 4),
                Text(_projectPath ?? 'No directory selected', style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
              ],
            ),
          ),
          ElevatedButton(
            onPressed: _pickProject,
            style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF8AB4F8), foregroundColor: Colors.white),
            child: const Text('Change'),
          ),
        ],
      ),
    );
  }

  Widget _buildSetupWizard(bool isBusy) {
    return Container(
      decoration: BoxDecoration(color: const Color(0xFF1E1E1E), borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFF3C4043))),
      child: Column(
        children: [
          Row(
            children: [
              _buildTab(0, 'Link Existing Repo', Icons.link),
              _buildTab(1, 'Create New Repo', Icons.add_circle_outline),
            ],
          ),
          Padding(
            padding: const EdgeInsets.all(32),
            child: _activeTab == 0
                ? Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Connect this folder to an existing GitHub repository.', style: TextStyle(color: Colors.grey)),
                      const SizedBox(height: 24),
                      Row(
                        children: [
                          Expanded(child: _buildTextField('Owner (Username)', _ownerCtrl, Icons.person_outline)),
                          const SizedBox(width: 16),
                          Expanded(child: _buildTextField('Repository Name', _repoCtrl, Icons.source_outlined)),
                        ],
                      ),
                      const SizedBox(height: 24),
                      ElevatedButton.icon(
                        onPressed: isBusy ? null : _linkExistingRepo,
                        icon: const Icon(Icons.cable),
                        label: const Text('Connect Remote'),
                        style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF8AB4F8), foregroundColor: Colors.white, minimumSize: const Size(200, 48)),
                      )
                    ],
                  )
                : Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Create a brand new private repository on your GitHub account.', style: TextStyle(color: Colors.grey)),
                      const SizedBox(height: 24),
                      _buildTextField('New Repository Name', _newRepoNameCtrl, Icons.create_new_folder_outlined),
                      const SizedBox(height: 24),
                      ElevatedButton.icon(
                        onPressed: isBusy ? null : _createNewRepo,
                        icon: const Icon(Icons.cloud_upload),
                        label: const Text('Create & Connect'),
                        style: ElevatedButton.styleFrom(backgroundColor: Colors.green, foregroundColor: Colors.white, minimumSize: const Size(200, 48)),
                      )
                    ],
                  ),
          )
        ],
      ),
    );
  }

  Widget _buildCommitFlow(GitState git, bool isBusy) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(color: const Color(0xFF1E1E1E), borderRadius: BorderRadius.circular(16), border: Border.all(color: const Color(0xFF3C4043))),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.check_circle, color: Colors.green),
              const SizedBox(width: 8),
              const Expanded(
                child: Text('Connected to GitHub', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold), overflow: TextOverflow.ellipsis),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: BoxDecoration(color: Colors.green.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(20), border: Border.all(color: Colors.green.withValues(alpha: 0.3))),
                child: Text(git.currentBranch, style: const TextStyle(color: Colors.green, fontWeight: FontWeight.bold)),
              )
            ],
          ),
          const SizedBox(height: 24),
          Row(
            children: [
              const Text('Changed Files:', style: TextStyle(color: Colors.white70)),
              const Spacer(),
              if (git.changedFiles.isNotEmpty)
                TextButton.icon(
                  onPressed: () {
                    setState(() {
                      if (_selectedFiles.length == git.changedFiles.length) {
                        _selectedFiles.clear();
                      } else {
                        _selectedFiles.addAll(git.changedFiles.map((e) => e.path));
                      }
                    });
                  },
                  icon: Icon(
                    _selectedFiles.length == git.changedFiles.length ? Icons.deselect : Icons.select_all,
                    color: const Color(0xFF8AB4F8), size: 16,
                  ),
                  label: Text(
                    _selectedFiles.length == git.changedFiles.length ? 'Deselect All' : 'Select All',
                    style: const TextStyle(color: Color(0xFF8AB4F8), fontSize: 12),
                  ),
                ),
            ],
          ),
          const SizedBox(height: 8),
          if (git.changedFiles.isEmpty)
            const Text('No changes detected in working tree.', style: TextStyle(color: Colors.grey, fontStyle: FontStyle.italic))
          else
            Container(
              constraints: const BoxConstraints(maxHeight: 400),
              decoration: BoxDecoration(color: const Color(0xFF131314), borderRadius: BorderRadius.circular(8)),
              child: ListView.builder(
                shrinkWrap: true,
                padding: const EdgeInsets.all(8),
                itemCount: git.changedFiles.length,
                itemBuilder: (context, i) {
                  final f = git.changedFiles[i];
                  final isSelected = _selectedFiles.contains(f.path);
                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 4),
                    child: Row(
                      children: [
                        Checkbox(
                          value: isSelected,
                          activeColor: const Color(0xFF8AB4F8),
                          onChanged: (val) {
                            setState(() {
                              if (val == true) _selectedFiles.add(f.path);
                              else _selectedFiles.remove(f.path);
                            });
                          },
                        ),
                        Text(f.statusLabel, style: TextStyle(color: f.status == 'M' ? Colors.orange : Colors.green, fontWeight: FontWeight.bold)),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Text(f.path, style: const TextStyle(color: Colors.grey, fontFamily: 'monospace'), overflow: TextOverflow.ellipsis),
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
          const SizedBox(height: 24),
          Row(
            children: [
              Expanded(child: _buildTextField('Commit Message', _commitMsgCtrl, Icons.edit)),
            ],
          ),
          const SizedBox(height: 24),
          Wrap(
            alignment: WrapAlignment.end,
            spacing: 12,
            runSpacing: 12,
            children: [
              if (_selectedFiles.isNotEmpty)
                ElevatedButton.icon(
                  onPressed: isBusy ? null : () async {
                    await ref.read(gitProvider.notifier).stageFiles(_selectedFiles.toList());
                    setState(() => _selectedFiles.clear());
                    _showSnack('Selected files staged!');
                  },
                  icon: const Icon(Icons.playlist_add_check),
                  label: const Text('Stage Selected'),
                  style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF8AB4F8).withValues(alpha: 0.2), foregroundColor: const Color(0xFF8AB4F8)),
                ),
              ElevatedButton.icon(
                onPressed: isBusy ? null : () => ref.read(gitProvider.notifier).stageAll(),
                icon: const Icon(Icons.library_add),
                label: const Text('Stage All'),
                style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF3C4043), foregroundColor: Colors.white),
              ),
              ElevatedButton.icon(
                onPressed: isBusy ? null : () {
                  if (_commitMsgCtrl.text.isEmpty) {
                    _showSnack('Please enter a commit message');
                    return;
                  }
                  ref.read(gitProvider.notifier).commit(_commitMsgCtrl.text);
                  _commitMsgCtrl.clear();
                },
                icon: const Icon(Icons.check),
                label: const Text('Commit'),
                style: ElevatedButton.styleFrom(backgroundColor: Colors.orangeAccent, foregroundColor: Colors.black),
              ),
              ElevatedButton.icon(
                onPressed: isBusy ? null : _safePush,
                icon: const Icon(Icons.cloud_upload),
                label: const Text('Push to Remote'),
                style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF8AB4F8), foregroundColor: Colors.white),
              ),
              ElevatedButton.icon(
                onPressed: isBusy ? null : () => ref.read(gitProvider.notifier).pull(),
                icon: const Icon(Icons.cloud_download),
                label: const Text('Pull from Remote'),
                style: ElevatedButton.styleFrom(backgroundColor: Colors.green, foregroundColor: Colors.white),
              ),
            ],
          )
        ],
      ),
    );
  }

  Widget _buildTab(int index, String title, IconData icon) {
    final isActive = _activeTab == index;
    return Expanded(
      child: GestureDetector(
        onTap: () => setState(() => _activeTab = index),
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 16),
          decoration: BoxDecoration(
            border: Border(bottom: BorderSide(color: isActive ? const Color(0xFF8AB4F8) : const Color(0xFF3C4043), width: 2)),
            color: isActive ? const Color(0xFF8AB4F8).withValues(alpha: 0.05) : Colors.transparent,
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(icon, color: isActive ? const Color(0xFF8AB4F8) : Colors.grey, size: 20),
              const SizedBox(width: 8),
              Text(title, style: TextStyle(color: isActive ? const Color(0xFF8AB4F8) : Colors.grey, fontWeight: FontWeight.bold)),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _showUpdateTokenDialog() async {
    final ctrl = TextEditingController();
    final result = await showDialog<String>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: const Color(0xFF1E1E1E),
        title: const Text('Update GitHub Token', style: TextStyle(color: Colors.white)),
        content: TextField(
          controller: ctrl,
          obscureText: true,
          style: const TextStyle(color: Colors.white),
          decoration: const InputDecoration(
            labelText: 'New Personal Access Token (PAT)',
            labelStyle: TextStyle(color: Colors.grey),
            enabledBorder: OutlineInputBorder(borderSide: BorderSide(color: Color(0xFF3C4043))),
            focusedBorder: OutlineInputBorder(borderSide: BorderSide(color: Color(0xFF8AB4F8))),
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel', style: TextStyle(color: Colors.grey))),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF8AB4F8)),
            onPressed: () => Navigator.pop(ctx, ctrl.text),
            child: const Text('Save', style: TextStyle(color: Colors.black)),
          ),
        ],
      )
    );
    
    if (result != null && result.isNotEmpty) {
      await _storage.write(key: 'github_access_token', value: result);
      _showSnack('GitHub Token securely updated.');
    }
  }

  Widget _buildProfileBadge() {
    return Row(
      children: [
        CircleAvatar(backgroundColor: const Color(0xFF8AB4F8).withValues(alpha: 0.2), child: const Icon(Icons.person, color: Color(0xFF8AB4F8))),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Signed in as', style: TextStyle(color: Colors.grey, fontSize: 12)),
              Text('@$_githubUsername', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 14)),
            ],
          ),
        ),
        IconButton(
          icon: const Icon(Icons.key, color: Colors.grey, size: 20),
          tooltip: 'Update GitHub Token',
          onPressed: _showUpdateTokenDialog,
        )
      ],
    );
  }


  Widget _buildRecommendationCard(String title, String desc, IconData icon, Color color) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withValues(alpha: 0.2)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: color, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title, style: TextStyle(color: color, fontWeight: FontWeight.bold, fontSize: 14)),
                const SizedBox(height: 4),
                Text(desc, style: TextStyle(color: color.withValues(alpha: 0.8), fontSize: 12, height: 1.4)),
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _buildTextField(String label, TextEditingController controller, IconData icon) {
    return TextField(
      controller: controller,
      style: const TextStyle(color: Colors.white, fontSize: 14),
      decoration: InputDecoration(
        labelText: label,
        labelStyle: TextStyle(color: Colors.grey.shade400, fontSize: 12),
        prefixIcon: Icon(icon, color: Colors.grey.shade500, size: 20),
        filled: true,
        fillColor: const Color(0xFF0F172A),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Colors.grey.shade800)),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Colors.blueAccent)),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      ),
    );
  }
}
