import 'dart:io';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../data/local/secure_storage_service.dart';
import '../../engines/git/git_notifier.dart';
import '../../data/remote/github_client.dart';
import '../../engines/scanner/scanner_engine.dart';
import '../../data/models/finding.dart';
import '../../core/utils/app_logger.dart';
import 'widgets/branch_panel.dart';

class GitPanelScreen extends ConsumerStatefulWidget {
  const GitPanelScreen({super.key});

  @override
  ConsumerState<GitPanelScreen> createState() => _GitPanelScreenState();
}

class _GitPanelScreenState extends ConsumerState<GitPanelScreen> {
  final _commitMsgCtrl    = TextEditingController();
  final _ownerCtrl        = TextEditingController();
  final _repoCtrl         = TextEditingController();
  final _newRepoNameCtrl  = TextEditingController();
  final _storage          = const FlutterSecureStorage();
  final _githubClient     = GitHubClient();

  String? _projectPath;
  String  _githubUsername = '';
  int     _activeTab      = 0; // 0 = Link Existing, 1 = Create New
  bool    _isPrivate      = true;
  bool    _showDiff       = false;
  String? _diffFile;
  final Set<String> _selectedFiles = {};

  @override
  void initState() {
    super.initState();
    _loadProfile();
  }

  Future<void> _loadProfile() async {
    final username = await storageService.getUsername();
    if (username != null) {
      setState(() => _githubUsername = username);
      _ownerCtrl.text = username;
    }
  }

  AppLogger get _logger => ref.read(appLoggerProvider.notifier);

  // ─── Project ────────────────────────────────────────────────────────────────

  Future<void> _pickProject() async {
    try {
      final dir = await getDirectoryPath();
      if (dir != null) {
        setState(() {
          _projectPath  = dir;
          _selectedFiles.clear();
          _showDiff     = false;
          _diffFile     = null;
        });
        await ref.read(gitProvider.notifier).loadProject(dir);
        await _ensureGitignore(dir);
      }
    } catch (e) {
      _snack('Error picking folder: $e');
    }
  }

  Future<void> _ensureGitignore(String dirPath) async {
    final file = File('$dirPath/.gitignore');
    if (!await file.exists()) {
      await file.writeAsString(
        '# Standard .gitignore generated by DevGate\n'
        '.env\n.env.local\nbuild/\n.dart_tool/\n.pub-cache/\n.packages\n'
        '*.log\nnode_modules/\n*.key\n*.pem\n',
      );
      _snack('Created a default .gitignore to protect secrets.');
      _logger.success('Auto-generated .gitignore at $dirPath');
    }
  }

  // ─── Repo setup ──────────────────────────────────────────────────────────────

  Future<void> _linkExistingRepo() async {
    if (_ownerCtrl.text.isEmpty || _repoCtrl.text.isEmpty) {
      _snack('Please fill Owner and Repo name.');
      return;
    }
    final token = await storageService.getToken();
    if (token == null) { _snack('No token found. Check Settings.'); return; }

    if (!ref.read(gitProvider).isGitRepo) {
      await ref.read(gitProvider.notifier).initRepo(_projectPath!);
    }
    await ref.read(gitProvider.notifier)
        .setRemoteWithToken(_ownerCtrl.text, _repoCtrl.text, token);
    _snack('Repository linked successfully!');
  }

  Future<void> _createNewRepo() async {
    if (_newRepoNameCtrl.text.isEmpty) {
      _snack('Please enter a repository name.');
      return;
    }
    _snack('Creating repository on GitHub...');
    final success = await _githubClient.createRepository(
      _newRepoNameCtrl.text,
      private: _isPrivate,
    );
    if (!success) {
      _snack('Failed — check if the name already exists.');
      return;
    }
    final token = await storageService.getToken();
    if (!ref.read(gitProvider).isGitRepo) {
      await ref.read(gitProvider.notifier).initRepo(_projectPath!);
    }
    await ref.read(gitProvider.notifier)
        .setRemoteWithToken(_githubUsername, _newRepoNameCtrl.text, token!);
    _snack('🎉 Repository created and linked!');
  }

  // ─── Safe push ───────────────────────────────────────────────────────────────

  Future<void> _safePush() async {
    if (_projectPath == null) return;
    _snack('Scanning for secrets before pushing...');
    _logger.info('Pre-push scan started...');

    await ref.read(scannerStateProvider.notifier).scanDirectories([_projectPath!]);

    final secrets = ref
        .read(scannerStateProvider)
        .findings
        .where((f) => f.type != FindingType.recommendation)
        .toList();

    if (secrets.isNotEmpty && mounted) {
      showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
          backgroundColor: const Color(0xFF1E1E1E),
          title: const Row(
            children: [
              Icon(Icons.warning_amber_rounded, color: Colors.redAccent),
              SizedBox(width: 8),
              Text('Security Risk Detected!',
                  style: TextStyle(color: Colors.redAccent, fontSize: 18)),
            ],
          ),
          content: Text(
            'Found ${secrets.length} potential secret(s) in your code.\n'
            'Review them in the Scanner tab before pushing.',
            style: const TextStyle(color: Colors.white70),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: const Text('Cancel Push',
                  style: TextStyle(color: Colors.grey)),
            ),
            TextButton(
              onPressed: () async {
                Navigator.pop(ctx);
                _snack('Override active. Pushing...');
                _logger.warning('Push override — user acknowledged ${secrets.length} finding(s)');
                await ref.read(gitProvider.notifier).push();
              },
              child: const Text('Push Anyway',
                  style: TextStyle(color: Colors.redAccent)),
            ),
          ],
        ),
      );
      return;
    }

    _snack('Scan passed ✓ — pushing to GitHub...');
    await ref.read(gitProvider.notifier).push();
  }

  // ─── Diff viewer ─────────────────────────────────────────────────────────────

  Future<void> _loadDiff(String? filePath) async {
    setState(() {
      _showDiff = true;
      _diffFile = filePath;
    });
    await ref.read(gitProvider.notifier).loadDiff(filePath: filePath);
  }

  // ─── Stash ───────────────────────────────────────────────────────────────────

  Future<void> _stash() async {
    await ref.read(gitProvider.notifier).stash();
    _snack('Changes stashed.');
  }

  Future<void> _stashPop() async {
    await ref.read(gitProvider.notifier).stashPop();
    _snack('Stash restored.');
  }

  // ─── Device Flow OAuth ───────────────────────────────────────────────────────

  Future<void> _showDeviceFlowDialog() async {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => _DeviceFlowDialog(
        githubClient: _githubClient,
        onSuccess: (token) async {
          await _storage.write(key: 'github_access_token', value: token);
          _snack('✅ GitHub authentication successful!');
          _logger.success('Device Flow OAuth completed successfully');
        },
      ),
    );
  }

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  void _snack(String msg) {
    if (mounted) {
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text(msg)));
    }
  }

  @override
  void dispose() {
    _commitMsgCtrl.dispose();
    _ownerCtrl.dispose();
    _repoCtrl.dispose();
    _newRepoNameCtrl.dispose();
    super.dispose();
  }

  // ─── Build ───────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final git   = ref.watch(gitProvider);
    final isBusy = git.operation != GitOperation.idle;

    return Scaffold(
      backgroundColor: const Color(0xFF131314),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final isMobile = constraints.maxWidth < 800;

          final mainContent = SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Workspace Integration',
                  style: TextStyle(
                      fontSize: 26,
                      fontWeight: FontWeight.bold,
                      color: Colors.white),
                ),
                const SizedBox(height: 6),
                const Text(
                  'Manage local code and sync securely with GitHub.',
                  style: TextStyle(color: Colors.grey, fontSize: 13),
                ),
                const SizedBox(height: 28),

                // Project picker
                _buildProjectPicker(),
                const SizedBox(height: 20),

                if (_projectPath != null) ...[
                  // Main workflow: setup or commit
                  if (!git.isGitRepo ||
                      git.remoteUrl.isEmpty ||
                      git.remoteUrl == 'No remote')
                    _buildSetupWizard(isBusy)
                  else ...[
                    _buildCommitFlow(git, isBusy),
                    const SizedBox(height: 20),
                    // Branch management
                    const BranchPanel(),
                    const SizedBox(height: 20),
                    // Stash controls
                    _buildStashRow(isBusy),
                    const SizedBox(height: 20),
                    // Diff viewer
                    if (_showDiff) _buildDiffViewer(git),
                  ],
                ],
              ],
            ),
          );

          final sidebar = Container(
            width: isMobile ? double.infinity : 300,
            decoration: BoxDecoration(
              color: const Color(0xFF1E1E1E),
              border: isMobile
                  ? const Border(
                      top: BorderSide(color: Color(0xFF3C4043)))
                  : const Border(
                      left: BorderSide(color: Color(0xFF3C4043))),
            ),
            padding: const EdgeInsets.all(24),
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildProfileBadge(),
                  const SizedBox(height: 16),
                  // Device Flow button
                  SizedBox(
                    width: double.infinity,
                    child: OutlinedButton.icon(
                      onPressed: _showDeviceFlowDialog,
                      icon: const Icon(Icons.login, size: 16),
                      label: const Text('Authenticate via GitHub',
                          style: TextStyle(fontSize: 13)),
                      style: OutlinedButton.styleFrom(
                        foregroundColor: const Color(0xFF8AB4F8),
                        side: const BorderSide(
                            color: Color(0xFF8AB4F8), width: 1),
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10)),
                      ),
                    ),
                  ),
                  const SizedBox(height: 28),
                  Row(
                    children: const [
                      Icon(Icons.auto_awesome,
                          color: Color(0xFF8AB4F8), size: 16),
                      SizedBox(width: 8),
                      Text('Smart Recommendations',
                          style: TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: Colors.white)),
                    ],
                  ),
                  const SizedBox(height: 14),
                  _buildDynamicRecommendations(git),
                  if (git.operationOutput.isNotEmpty) ...[
                    const SizedBox(height: 24),
                    const Text('Terminal Output',
                        style: TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.bold,
                            color: Colors.white)),
                    const SizedBox(height: 8),
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                          color: Colors.black45,
                          borderRadius: BorderRadius.circular(8)),
                      child: SelectableText(
                        git.operationOutput,
                        style: TextStyle(
                          color: git.hasError
                              ? Colors.redAccent
                              : Colors.greenAccent,
                          fontFamily: 'monospace',
                          fontSize: 12,
                        ),
                      ),
                    ),
                  ],
                ],
              ),
            ),
          );

          if (isMobile) {
            return SingleChildScrollView(
              child: Column(children: [mainContent, sidebar]),
            );
          }

          return Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(flex: 2, child: mainContent),
              sidebar,
            ],
          );
        },
      ),
    );
  }

  // ─── Project picker ──────────────────────────────────────────────────────────

  Widget _buildProjectPicker() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF3C4043)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: BoxDecoration(
              color: const Color(0xFF8AB4F8).withValues(alpha: 0.1),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.folder, color: Color(0xFF8AB4F8)),
          ),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Current Directory',
                    style: TextStyle(color: Colors.grey, fontSize: 11)),
                const SizedBox(height: 2),
                Text(
                  _projectPath ?? 'No directory selected',
                  style: const TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontWeight: FontWeight.bold),
                  overflow: TextOverflow.ellipsis,
                ),
              ],
            ),
          ),
          const SizedBox(width: 12),
          ElevatedButton(
            onPressed: _pickProject,
            style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF8AB4F8),
                foregroundColor: Colors.white),
            child: const Text('Browse'),
          ),
        ],
      ),
    );
  }

  // ─── Setup wizard ────────────────────────────────────────────────────────────

  Widget _buildSetupWizard(bool isBusy) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF3C4043)),
      ),
      child: Column(
        children: [
          Row(
            children: [
              _buildTab(0, 'Link Existing', Icons.link),
              _buildTab(1, 'Create New', Icons.add_circle_outline),
            ],
          ),
          Padding(
            padding: const EdgeInsets.all(28),
            child: _activeTab == 0
                ? Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Connect to an existing GitHub repo.',
                          style: TextStyle(color: Colors.grey)),
                      const SizedBox(height: 20),
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                                'Owner (Username)', _ownerCtrl,
                                Icons.person_outline),
                          ),
                          const SizedBox(width: 14),
                          Expanded(
                            child: _buildTextField(
                                'Repository Name', _repoCtrl,
                                Icons.source_outlined),
                          ),
                        ],
                      ),
                      const SizedBox(height: 20),
                      ElevatedButton.icon(
                        onPressed: isBusy ? null : _linkExistingRepo,
                        icon: const Icon(Icons.cable),
                        label: const Text('Connect Remote'),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF8AB4F8),
                          foregroundColor: Colors.white,
                          minimumSize: const Size(200, 48),
                        ),
                      ),
                    ],
                  )
                : Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Create a new GitHub repository.',
                          style: TextStyle(color: Colors.grey)),
                      const SizedBox(height: 20),
                      _buildTextField('New Repository Name',
                          _newRepoNameCtrl, Icons.create_new_folder_outlined),
                      const SizedBox(height: 14),
                      Container(
                        decoration: BoxDecoration(
                          color: const Color(0xFF0F172A),
                          borderRadius: BorderRadius.circular(12),
                          border:
                              Border.all(color: Colors.grey.shade800),
                        ),
                        child: SwitchListTile(
                          title: const Text('Private Repository',
                              style: TextStyle(
                                  color: Colors.white, fontSize: 13)),
                          subtitle: const Text(
                              'Only you can see and commit.',
                              style: TextStyle(
                                  color: Colors.grey, fontSize: 11)),
                          value: _isPrivate,
                          activeThumbColor: const Color(0xFF8AB4F8),
                          onChanged: (v) =>
                              setState(() => _isPrivate = v),
                        ),
                      ),
                      const SizedBox(height: 20),
                      ElevatedButton.icon(
                        onPressed: isBusy ? null : _createNewRepo,
                        icon: const Icon(Icons.cloud_upload),
                        label: const Text('Create & Connect'),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.green,
                          foregroundColor: Colors.white,
                          minimumSize: const Size(200, 48),
                        ),
                      ),
                    ],
                  ),
          ),
        ],
      ),
    );
  }

  // ─── Commit flow ─────────────────────────────────────────────────────────────

  Widget _buildCommitFlow(GitState git, bool isBusy) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF3C4043)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Row(
            children: [
              const Icon(Icons.check_circle, color: Colors.green, size: 20),
              const SizedBox(width: 8),
              const Expanded(
                child: Text('Connected to GitHub',
                    style: TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                        fontWeight: FontWeight.bold)),
              ),
              // Branch badge
              Container(
                padding: const EdgeInsets.symmetric(
                    horizontal: 10, vertical: 5),
                decoration: BoxDecoration(
                  color: Colors.green.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(
                      color: Colors.green.withValues(alpha: 0.3)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.account_tree,
                        size: 12, color: Colors.greenAccent),
                    const SizedBox(width: 4),
                    Text(git.currentBranch,
                        style: const TextStyle(
                            color: Colors.greenAccent,
                            fontWeight: FontWeight.bold,
                            fontSize: 12)),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),

          // Changed files
          Row(
            children: [
              const Text('Changed Files:',
                  style: TextStyle(color: Colors.white70, fontSize: 13)),
              const Spacer(),
              if (git.changedFiles.isNotEmpty) ...[
                // Diff button
                TextButton.icon(
                  onPressed: () => _loadDiff(null),
                  icon: const Icon(Icons.difference, size: 14),
                  label: const Text('View Diff',
                      style: TextStyle(fontSize: 12)),
                  style: TextButton.styleFrom(
                      foregroundColor: const Color(0xFF8AB4F8)),
                ),
                TextButton.icon(
                  onPressed: () {
                    setState(() {
                      if (_selectedFiles.length == git.changedFiles.length) {
                        _selectedFiles.clear();
                      } else {
                        _selectedFiles.addAll(
                            git.changedFiles.map((f) => f.path));
                      }
                    });
                  },
                  icon: Icon(
                    _selectedFiles.length == git.changedFiles.length
                        ? Icons.deselect
                        : Icons.select_all,
                    size: 14,
                    color: const Color(0xFF8AB4F8),
                  ),
                  label: Text(
                    _selectedFiles.length == git.changedFiles.length
                        ? 'Deselect All'
                        : 'Select All',
                    style: const TextStyle(
                        color: Color(0xFF8AB4F8), fontSize: 12),
                  ),
                ),
              ],
            ],
          ),
          const SizedBox(height: 8),

          if (git.changedFiles.isEmpty)
            const Text(
              'No changes detected in working tree.',
              style:
                  TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
            )
          else
            Container(
              constraints: const BoxConstraints(maxHeight: 360),
              decoration: BoxDecoration(
                color: const Color(0xFF131314),
                borderRadius: BorderRadius.circular(8),
              ),
              child: ListView.builder(
                shrinkWrap: true,
                padding: const EdgeInsets.all(8),
                itemCount: git.changedFiles.length,
                itemBuilder: (_, i) {
                  final f = git.changedFiles[i];
                  final isSelected = _selectedFiles.contains(f.path);
                  final statusColor = _statusColor(f.status);

                  return InkWell(
                    onTap: () => setState(() {
                      if (isSelected) {
                        _selectedFiles.remove(f.path);
                      } else {
                        _selectedFiles.add(f.path);
                      }
                    }),
                    onSecondaryTap: () => _loadDiff(f.path),
                    child: Padding(
                      padding: const EdgeInsets.symmetric(
                          vertical: 4, horizontal: 4),
                      child: Row(
                        children: [
                          Checkbox(
                            value: isSelected,
                            activeColor: const Color(0xFF8AB4F8),
                            onChanged: (v) => setState(() {
                              if (v == true) {
                                _selectedFiles.add(f.path);
                              } else {
                                _selectedFiles.remove(f.path);
                              }
                            }),
                          ),
                          Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 6, vertical: 2),
                            decoration: BoxDecoration(
                              color: statusColor.withValues(alpha: 0.15),
                              borderRadius: BorderRadius.circular(4),
                            ),
                            child: Text(
                              f.statusLabel,
                              style: TextStyle(
                                  color: statusColor,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 11),
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: Text(
                              f.path,
                              style: const TextStyle(
                                  color: Colors.grey,
                                  fontFamily: 'monospace',
                                  fontSize: 12),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          // Diff icon on hover
                          IconButton(
                            iconSize: 14,
                            tooltip: 'View diff',
                            icon: const Icon(Icons.difference_outlined,
                                color: Colors.white24),
                            onPressed: () => _loadDiff(f.path),
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),

          const SizedBox(height: 20),
          _buildTextField(
              'Commit Message', _commitMsgCtrl, Icons.edit_note),
          const SizedBox(height: 20),

          // Action buttons
          Wrap(
            alignment: WrapAlignment.end,
            spacing: 10,
            runSpacing: 10,
            children: [
              if (_selectedFiles.isNotEmpty)
                ElevatedButton.icon(
                  onPressed: isBusy
                      ? null
                      : () async {
                          await ref
                              .read(gitProvider.notifier)
                              .stageFiles(_selectedFiles.toList());
                          setState(() => _selectedFiles.clear());
                          _snack('Selected files staged!');
                        },
                  icon: const Icon(Icons.playlist_add_check, size: 16),
                  label: const Text('Stage Selected'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor:
                        const Color(0xFF8AB4F8).withValues(alpha: 0.15),
                    foregroundColor: const Color(0xFF8AB4F8),
                  ),
                ),
              ElevatedButton.icon(
                onPressed: isBusy
                    ? null
                    : () => ref.read(gitProvider.notifier).stageAll(),
                icon: const Icon(Icons.library_add, size: 16),
                label: const Text('Stage All'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF3C4043),
                  foregroundColor: Colors.white,
                ),
              ),
              ElevatedButton.icon(
                onPressed: isBusy
                    ? null
                    : () {
                        if (_commitMsgCtrl.text.trim().isEmpty) {
                          _snack('Enter a commit message first.');
                          return;
                        }
                        ref
                            .read(gitProvider.notifier)
                            .commit(_commitMsgCtrl.text.trim());
                        _commitMsgCtrl.clear();
                      },
                icon: const Icon(Icons.check, size: 16),
                label: const Text('Commit'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.orangeAccent,
                  foregroundColor: Colors.black,
                ),
              ),
              ElevatedButton.icon(
                onPressed: isBusy ? null : _safePush,
                icon: const Icon(Icons.cloud_upload, size: 16),
                label: const Text('Safe Push'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF8AB4F8),
                  foregroundColor: Colors.white,
                ),
              ),
              ElevatedButton.icon(
                onPressed: isBusy
                    ? null
                    : () => ref.read(gitProvider.notifier).pull(),
                icon: const Icon(Icons.cloud_download, size: 16),
                label: const Text('Pull'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.green,
                  foregroundColor: Colors.white,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ─── Stash row ───────────────────────────────────────────────────────────────

  Widget _buildStashRow(bool isBusy) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
      decoration: BoxDecoration(
        color: const Color(0xFF1E1E1E),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF3C4043)),
      ),
      child: Row(
        children: [
          const Icon(Icons.save_outlined, color: Colors.grey, size: 18),
          const SizedBox(width: 10),
          const Text('Stash',
              style: TextStyle(
                  color: Colors.white70,
                  fontWeight: FontWeight.w600,
                  fontSize: 14)),
          const SizedBox(width: 6),
          const Text('— save work-in-progress without committing',
              style: TextStyle(color: Colors.grey, fontSize: 12)),
          const Spacer(),
          OutlinedButton.icon(
            onPressed: isBusy ? null : _stash,
            icon: const Icon(Icons.arrow_downward, size: 14),
            label: const Text('Stash Changes', style: TextStyle(fontSize: 12)),
            style: OutlinedButton.styleFrom(
              foregroundColor: Colors.grey,
              side: const BorderSide(color: Color(0xFF3C4043)),
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            ),
          ),
          const SizedBox(width: 8),
          OutlinedButton.icon(
            onPressed: isBusy ? null : _stashPop,
            icon: const Icon(Icons.arrow_upward, size: 14),
            label: const Text('Pop Stash', style: TextStyle(fontSize: 12)),
            style: OutlinedButton.styleFrom(
              foregroundColor: const Color(0xFF8AB4F8),
              side: const BorderSide(color: Color(0xFF8AB4F8)),
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            ),
          ),
        ],
      ),
    );
  }

  // ─── Diff viewer ─────────────────────────────────────────────────────────────

  Widget _buildDiffViewer(GitState git) {
    final diff = git.diffOutput;

    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF0A0A0B),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFF3C4043)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: const BoxDecoration(
              color: Color(0xFF1E1E1E),
              borderRadius:
                  BorderRadius.vertical(top: Radius.circular(16)),
              border: Border(
                  bottom: BorderSide(color: Color(0xFF3C4043))),
            ),
            child: Row(
              children: [
                const Icon(Icons.difference, color: Color(0xFF8AB4F8), size: 16),
                const SizedBox(width: 8),
                Text(
                  _diffFile != null
                      ? 'Diff: ${_diffFile!.split('/').last}'
                      : 'Working Tree Diff',
                  style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                      fontSize: 13),
                ),
                const Spacer(),
                IconButton(
                  iconSize: 16,
                  icon: const Icon(Icons.close, color: Colors.grey),
                  onPressed: () {
                    setState(() {
                      _showDiff = false;
                      _diffFile = null;
                    });
                    ref.read(gitProvider.notifier).clearDiff();
                  },
                ),
              ],
            ),
          ),
          // Diff content
          SizedBox(
            height: 280,
            child: diff.isEmpty
                ? const Center(
                    child: Text('No diff available.',
                        style: TextStyle(color: Colors.grey)))
                : SingleChildScrollView(
                    padding: const EdgeInsets.all(12),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: diff.split('\n').map((line) {
                        Color lineColor = Colors.white54;
                        Color bgColor = Colors.transparent;
                        if (line.startsWith('+') && !line.startsWith('+++')) {
                          lineColor = Colors.greenAccent;
                          bgColor = Colors.green.withValues(alpha: 0.06);
                        } else if (line.startsWith('-') &&
                            !line.startsWith('---')) {
                          lineColor = Colors.redAccent;
                          bgColor = Colors.red.withValues(alpha: 0.06);
                        } else if (line.startsWith('@@')) {
                          lineColor = Colors.blueAccent;
                        } else if (line.startsWith('diff')) {
                          lineColor = const Color(0xFF8AB4F8);
                        }
                        return Container(
                          width: double.infinity,
                          color: bgColor,
                          padding: const EdgeInsets.symmetric(
                              horizontal: 4, vertical: 1),
                          child: Text(
                            line,
                            style: TextStyle(
                              color: lineColor,
                              fontFamily: 'monospace',
                              fontSize: 11,
                            ),
                          ),
                        );
                      }).toList(),
                    ),
                  ),
          ),
        ],
      ),
    );
  }

  // ─── Sidebar widgets ─────────────────────────────────────────────────────────

  Widget _buildProfileBadge() {
    return Row(
      children: [
        CircleAvatar(
          backgroundColor:
              const Color(0xFF8AB4F8).withValues(alpha: 0.15),
          child:
              const Icon(Icons.person, color: Color(0xFF8AB4F8)),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Signed in as',
                  style: TextStyle(color: Colors.grey, fontSize: 11)),
              Text(
                '@$_githubUsername',
                style: const TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 14),
              ),
            ],
          ),
        ),
        IconButton(
          icon: const Icon(Icons.key, color: Colors.grey, size: 18),
          tooltip: 'Update Token',
          onPressed: _showUpdateTokenDialog,
        ),
      ],
    );
  }

  Widget _buildDynamicRecommendations(GitState git) {
    final scanState = ref.watch(scannerStateProvider);
    final secrets = scanState.findings
        .where((f) => f.type != FindingType.recommendation)
        .toList();
    final criticals =
        secrets.where((f) => f.severity == Severity.critical).toList();

    final cards = <Widget>[];

    if (criticals.isNotEmpty) {
      cards.add(_recCard(
        '🔴 ${criticals.length} Critical Secret(s)!',
        'Found: ${criticals.map((f) => f.label).toSet().join(', ')}. Remove before pushing.',
        Icons.key_off_outlined,
        Colors.red,
      ));
    } else if (secrets.isNotEmpty) {
      cards.add(_recCard(
        '🟠 ${secrets.length} Potential Secret(s)',
        'In: ${secrets.map((f) => f.filePath.split('/').last).toSet().take(3).join(', ')}. Check Scanner tab.',
        Icons.warning_amber_rounded,
        Colors.orange,
      ));
    }

    if (_projectPath != null &&
        !File('$_projectPath/.gitignore').existsSync()) {
      cards.add(_recCard(
        '⚠️ Missing .gitignore',
        'Without it, secrets and build files may be pushed accidentally.',
        Icons.shield_outlined,
        Colors.orange,
      ));
    }

    if (_selectedFiles
        .any((f) => f.startsWith('build/') || f.contains('.dart_tool'))) {
      cards.add(_recCard(
        '🟠 Build Artifacts Staged',
        'build/ and .dart_tool/ are generated. Do not push them.',
        Icons.folder_off_outlined,
        Colors.deepOrange,
      ));
    }

    final msg = _commitMsgCtrl.text.trim();
    if (git.changedFiles.isNotEmpty && msg.isNotEmpty && msg.length < 10) {
      cards.add(_recCard(
        '✏️ Improve Commit Message',
        '"$msg" is very short. Describe what changed clearly.',
        Icons.edit_note,
        const Color(0xFF8AB4F8),
      ));
    }

    if (git.changedFiles.length > 20) {
      cards.add(_recCard(
        '📦 Large Commit Detected',
        '${git.changedFiles.length} files. Consider splitting into smaller commits.',
        Icons.commit,
        Colors.amber,
      ));
    }

    if (cards.isEmpty && secrets.isEmpty) {
      cards.add(_recCard(
        '✅ All Clear!',
        git.changedFiles.isEmpty
            ? 'Working tree is clean. No secrets found.'
            : 'No secrets detected. Safe to push!',
        Icons.verified_outlined,
        Colors.green,
      ));
    }

    return Column(
      children: [
        for (int i = 0; i < cards.length; i++) ...[
          cards[i],
          if (i < cards.length - 1) const SizedBox(height: 10),
        ],
      ],
    );
  }

  Widget _recCard(
    String title,
    String desc,
    IconData icon,
    Color color,
  ) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: color.withValues(alpha: 0.2)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: color, size: 18),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: TextStyle(
                        color: color,
                        fontWeight: FontWeight.bold,
                        fontSize: 13)),
                const SizedBox(height: 3),
                Text(desc,
                    style: TextStyle(
                        color: color.withValues(alpha: 0.75),
                        fontSize: 11,
                        height: 1.4)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ─── Update token dialog ─────────────────────────────────────────────────────

  Future<void> _showUpdateTokenDialog() async {
    final ctrl = TextEditingController();
    final result = await showDialog<String>(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: const Color(0xFF1E1E1E),
        title: const Text('Update GitHub Token',
            style: TextStyle(color: Colors.white)),
        content: TextField(
          controller: ctrl,
          obscureText: true,
          style: const TextStyle(color: Colors.white),
          decoration: const InputDecoration(
            labelText: 'New Personal Access Token (PAT)',
            labelStyle: TextStyle(color: Colors.grey),
            enabledBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0xFF3C4043))),
            focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0xFF8AB4F8))),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child:
                const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF8AB4F8)),
            onPressed: () => Navigator.pop(ctx, ctrl.text),
            child: const Text('Save',
                style: TextStyle(color: Colors.black)),
          ),
        ],
      ),
    );
    if (result != null && result.isNotEmpty) {
      await storageService.saveToken(result);
      _snack('GitHub Token updated securely.');
      _logger.success('GitHub token updated');
    }
  }

  // ─── Helper builders ─────────────────────────────────────────────────────────

  Widget _buildTab(int index, String title, IconData icon) {
    final active = _activeTab == index;
    return Expanded(
      child: GestureDetector(
        onTap: () => setState(() => _activeTab = index),
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 14),
          decoration: BoxDecoration(
            border: Border(
              bottom: BorderSide(
                color:
                    active ? const Color(0xFF8AB4F8) : const Color(0xFF3C4043),
                width: 2,
              ),
            ),
            color: active
                ? const Color(0xFF8AB4F8).withValues(alpha: 0.05)
                : Colors.transparent,
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(icon,
                  color:
                      active ? const Color(0xFF8AB4F8) : Colors.grey,
                  size: 18),
              const SizedBox(width: 8),
              Text(
                title,
                style: TextStyle(
                  color: active ? const Color(0xFF8AB4F8) : Colors.grey,
                  fontWeight: FontWeight.bold,
                  fontSize: 13,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(
    String label,
    TextEditingController controller,
    IconData icon,
  ) {
    return TextField(
      controller: controller,
      style: const TextStyle(color: Colors.white, fontSize: 13),
      decoration: InputDecoration(
        labelText: label,
        labelStyle:
            TextStyle(color: Colors.grey.shade400, fontSize: 12),
        prefixIcon:
            Icon(icon, color: Colors.grey.shade500, size: 18),
        filled: true,
        fillColor: const Color(0xFF0F172A),
        border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none),
        enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: Colors.grey.shade800)),
        focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide:
                const BorderSide(color: Colors.blueAccent)),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      ),
    );
  }

  Color _statusColor(String status) {
    switch (status.trim()) {
      case 'M':  return Colors.orange;
      case 'A':  return Colors.green;
      case 'D':  return Colors.redAccent;
      case 'R':  return Colors.blueAccent;
      case 'U':  return Colors.purpleAccent;
      default:   return Colors.grey;
    }
  }
}

// ─── Device Flow OAuth Dialog ─────────────────────────────────────────────────

class _DeviceFlowDialog extends StatefulWidget {
  final GitHubClient githubClient;
  final void Function(String token) onSuccess;

  const _DeviceFlowDialog({
    required this.githubClient,
    required this.onSuccess,
  });

  @override
  State<_DeviceFlowDialog> createState() => _DeviceFlowDialogState();
}

class _DeviceFlowDialogState extends State<_DeviceFlowDialog> {
  _FlowStep _step = _FlowStep.loading;
  String _userCode = '';
  String _verificationUri = '';
  String _errorMessage = '';

  @override
  void initState() {
    super.initState();
    _startFlow();
  }

  Future<void> _startFlow() async {
    try {
      final data = await widget.githubClient.requestDeviceCode();
      if (!mounted) return;

      setState(() {
        _userCode        = data['user_code'] ?? '';
        _verificationUri = data['verification_uri'] ?? 'https://github.com/login/device';
        _step            = _FlowStep.waitingForUser;
      });

      // Poll in background.
      final deviceCode = data['device_code'] as String;
      final interval   = (data['interval'] as int?) ?? 5;
      final token = await widget.githubClient.pollForToken(deviceCode, interval);

      if (!mounted) return;
      if (token != null) {
        widget.onSuccess(token);
        Navigator.of(context).pop();
      } else {
        setState(() {
          _step = _FlowStep.error;
          _errorMessage = 'Authorization failed or expired. Please try again.';
        });
      }
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _step = _FlowStep.error;
        _errorMessage = 'Could not connect to GitHub: $e';
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: const Color(0xFF1E1E1E),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      title: const Row(
        children: [
          Icon(Icons.login, color: Color(0xFF8AB4F8)),
          SizedBox(width: 10),
          Text('Sign in with GitHub',
              style: TextStyle(color: Colors.white, fontSize: 18)),
        ],
      ),
      content: SizedBox(
        width: 380,
        child: _buildContent(),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
        ),
      ],
    );
  }

  Widget _buildContent() {
    switch (_step) {
      case _FlowStep.loading:
        return const SizedBox(
          height: 120,
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                CircularProgressIndicator(color: Color(0xFF8AB4F8)),
                SizedBox(height: 16),
                Text('Connecting to GitHub...',
                    style: TextStyle(color: Colors.grey)),
              ],
            ),
          ),
        );

      case _FlowStep.waitingForUser:
        return Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text(
              '1. Copy the code below\n2. Open the link\n3. Enter the code on GitHub',
              style: TextStyle(color: Colors.white70, fontSize: 13, height: 1.5),
            ),
            const SizedBox(height: 20),
            // User code display
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
              decoration: BoxDecoration(
                color: const Color(0xFF8AB4F8).withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                    color: const Color(0xFF8AB4F8).withValues(alpha: 0.4)),
              ),
              child: Text(
                _userCode,
                style: const TextStyle(
                  color: Color(0xFF8AB4F8),
                  fontSize: 28,
                  fontWeight: FontWeight.bold,
                  fontFamily: 'monospace',
                  letterSpacing: 6,
                ),
              ),
            ),
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: () async {
                  final uri = Uri.parse(_verificationUri);
                  if (await canLaunchUrl(uri)) await launchUrl(uri);
                },
                icon: const Icon(Icons.open_in_new, size: 16),
                label: Text(
                  'Open $_verificationUri',
                  overflow: TextOverflow.ellipsis,
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.green,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10)),
                ),
              ),
            ),
            const SizedBox(height: 16),
            const Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                SizedBox(
                  width: 14,
                  height: 14,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    color: Colors.grey,
                  ),
                ),
                SizedBox(width: 10),
                Text('Waiting for authorization...',
                    style: TextStyle(color: Colors.grey, fontSize: 12)),
              ],
            ),
          ],
        );

      case _FlowStep.error:
        return Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.error_outline, color: Colors.redAccent, size: 48),
            const SizedBox(height: 16),
            Text(
              _errorMessage,
              style: const TextStyle(color: Colors.white70, fontSize: 13),
              textAlign: TextAlign.center,
            ),
          ],
        );
    }
  }
}

enum _FlowStep { loading, waitingForUser, error }
